"""empty message

Revision ID: 40026e1c3db5
Revises: 2d7346a90e72
Create Date: 2020-01-23 17:53:17.787815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40026e1c3db5'
down_revision = '2d7346a90e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
