"""empty message

Revision ID: 469e3c80e81a
Revises: df9adaa289df
Create Date: 2020-01-27 14:41:09.240336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469e3c80e81a'
down_revision = 'df9adaa289df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'post_id')
    # ### end Alembic commands ###
