"""empty message

Revision ID: 62071b198bd7
Revises: 469e3c80e81a
Create Date: 2020-01-27 15:42:18.647834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62071b198bd7'
down_revision = '469e3c80e81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
