"""empty message

Revision ID: 75de41160f20
Revises: f76f8f61619e
Create Date: 2020-01-24 17:22:08.558093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75de41160f20'
down_revision = 'f76f8f61619e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('birthday', sa.String(length=255), nullable=False))
    op.add_column('profile', sa.Column('ddress', sa.String(length=255), nullable=False))
    op.add_column('profile', sa.Column('occupation', sa.String(length=255), nullable=False))
    op.add_column('profile', sa.Column('skills', sa.String(length=255), nullable=False))
    op.add_column('profile', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'profile', 'users', ['user_id'], ['id'])
    op.drop_column('profile', 'nicname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('nicname', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_column('profile', 'user_id')
    op.drop_column('profile', 'skills')
    op.drop_column('profile', 'occupation')
    op.drop_column('profile', 'ddress')
    op.drop_column('profile', 'birthday')
    # ### end Alembic commands ###
