"""empty message

Revision ID: 95e499c2fcd1
Revises: 865adaf9c0f2
Create Date: 2020-01-23 14:50:29.005761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95e499c2fcd1'
down_revision = '865adaf9c0f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(length=255), nullable=False))
    op.drop_column('users', 'fulname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fulname', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
