"""empty message

Revision ID: df9adaa289df
Revises: eabb3b9a8685
Create Date: 2020-01-24 17:57:04.068311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9adaa289df'
down_revision = 'eabb3b9a8685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('profile', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'updated_at')
    op.drop_column('profile', 'created_at')
    # ### end Alembic commands ###
