"""empty message

Revision ID: eabb3b9a8685
Revises: 75de41160f20
Create Date: 2020-01-24 17:55:30.808850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eabb3b9a8685'
down_revision = '75de41160f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('address', sa.String(length=255), nullable=False))
    op.drop_column('profile', 'ddress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('ddress', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('profile', 'address')
    # ### end Alembic commands ###
